### ISSUE TITLE
리드미 추가

### ISSUE THREAD

**Issue by GeunSam2** [DAALZZWI/NewsApi#2]
리드미에 프로젝트에 대한 간단한 설명을 추가해주세요.
리드미는 지속적으로 업데이트 되어야 해요.

지금 시점에서는 프로젝트 설명과 서버 실행 방법이 기술되면 좋을 것 같아요.

**Comment by DAALZZWI** [comment]
네 알겠습니다!

2023년 3월 24일 (금) 오후 1:41, GeunSam2 (Gray) ***@***.***>님이 작성:

**Comment by GeunSam2** [comment]
이거 PR도 동시에 열리면 좋을거 같은데요
